name: Deploy React App to Google Cloud Run

on:
  push:
    branches:
      - main  # Change to your default branch if it's not 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Adjust if you're using a different version

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Google Container Registry
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-react-app-name .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-react-app-name

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy your-react-app-name --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-react-app-name --platform managed --region us-central1 --allow-unauthenticated